import type {
  Service,
  Promotion,
  ContactInfo,
  GreenCardFeature,
} from "@/types";

export const SITE_CONFIG = {
  name: "Clínica Hispana Nueva Salud Gessner",
  shortName: "Nueva Salud Gessner",
  tagline: "Clínica Hispana en Houston, TX",
  description:
    "Clínica Hispana Nueva Salud Gessner es la clínica hispana de confianza en Houston. Atención médica profesional en español para toda la familia. Exámenes médicos para Green Card (I-693) autorizados por USCIS.",
  baseUrl: "https://www.clinicagessner.com",
  locale: "es-MX",
} as const;

// Servicios con más demanda en Search Console. Se enlazan desde el footer para
// que cada uno reciba un enlace interno desde todas las páginas del sitio.
export const FOOTER_SERVICE_SLUGS = [
  "ginecologia",
  "ultrasonido",
  "examenes-inmigracion",
  "sueros-vitaminados",
  "vacunas",
  "unas-encarnadas",
  "examenes-sangre",
  "prueba-tuberculosis",
] as const;

export const CONTACT_INFO: ContactInfo = {
  address: "1914 Gessner Rd Ste B, Houston, TX 77080",
  phone: "+1 (346) 226-5820",
  // Número oficial de WhatsApp (el mismo que publica el perfil de Google
  // Business). El swap de CallRail solo aplica a llamadas tel:, nunca a este.
  whatsapp: "+1 (832) 831-4016",
  hours: "Lunes a Domingo: 9:00 AM - 9:00 PM",
  googleMapsUrl:
    "https://www.google.com/maps/place/CLINICA+HISPANA+NUEVA+SALUD+GESSNER/@29.806681,-95.5442136,17z/data=!3m1!4b1!4m6!3m5!1s0x8640c4de999b36b5:0xdc9d14200d006777!8m2!3d29.806681!4d-95.5442136!16s%2Fg%2F11c58dkqrc?entry=ttu",
  googleReviewUrl:
    "https://search.google.com/local/writereview?placeid=ChIJtTabmd7EQIYRd2cADSAUndw",
};

export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/clinicanuevasaludgessner/",
  facebook: "https://www.facebook.com/profile.php?id=61587230040182",
} as const;

// SERVICES - Servicios médicos de la clínica. Los textos (título visible,
// descripción, cuerpo y puntos clave, es/en) viven en src/messages/<lang>.json
// (`serviceData`), que es lo que se renderiza; aquí solo quedan los datos de
// estructura. Antes se duplicaban aquí y el duplicado no se publicaba.
export const SERVICES: Service[] = [
  {
    id: "condiciones-cronicas",
    slug: "condiciones-cronicas",
    title: "Control de Diabetes, Hipertensión y Colesterol",
    shortTitle: "Crónicas",
    icon: "Activity",
    image: "/images/services/condiciones-cronicas.webp",
    category: "medicina-general",
    highlighted: true,
    order: 1,
  },
  {
    id: "tiroides",
    slug: "tiroides",
    title: "Exámenes y Tratamiento de la Tiroides",
    shortTitle: "Tiroides",
    icon: "Thermometer",
    image: "/images/services/tiroides.webp",
    category: "medicina-general",
    order: 2,
  },
  {
    id: "alergias",
    slug: "alergias",
    title: "Exámenes y Tratamiento de Alergias",
    shortTitle: "Alergias",
    icon: "Leaf",
    image: "/images/services/alergias.webp",
    category: "medicina-general",
    order: 3,
  },
  {
    id: "enfermedades-respiratorias",
    slug: "enfermedades-respiratorias",
    title: "Pruebas de Flu y COVID y Enfermedades Respiratorias",
    shortTitle: "Respiratorias",
    icon: "Wind",
    image: "/images/services/enfermedades-respiratorias.webp",
    category: "medicina-general",
    order: 4,
  },
  {
    id: "examen-fisico-escolar",
    slug: "examen-fisico-escolar",
    title: "Chequeos Físicos Escolares y Deportivos",
    shortTitle: "Físico Escolar",
    icon: "ClipboardList",
    image: "/images/services/examen-fisico-escolar.webp",
    category: "examenes",
    order: 5,
  },
  {
    id: "ginecologia",
    slug: "ginecologia",
    related: ["ultrasonido", "prueba-embarazo", "anticonceptivos", "enfermedades-transmision-sexual"],
    title: "Ginecólogo en Español Cerca de Ti en Houston",
    shortTitle: "Ginecología",
    icon: "Flower2",
    image: "/images/services/ginecologia.webp",
    category: "salud-mujer",
    highlighted: true,
    order: 6,
  },
  {
    id: "prueba-embarazo",
    slug: "prueba-embarazo",
    title: "Examen y Diagnóstico de Embarazo",
    shortTitle: "Embarazo",
    icon: "Baby",
    image: "/images/services/prueba-embarazo.webp",
    category: "salud-mujer",
    order: 7,
  },
  {
    id: "anticonceptivos",
    slug: "anticonceptivos",
    title: "Tratamientos Anticonceptivos",
    shortTitle: "Anticonceptivos",
    icon: "Tablets",
    image: "/images/services/anticonceptivos.webp",
    category: "salud-mujer",
    order: 8,
  },
  {
    id: "extraccion-implantes",
    slug: "extraccion-implantes",
    title: "Extracción de Implantes Subdérmicos",
    shortTitle: "Implantes",
    icon: "Bandage",
    image: "/images/services/extraccion-implantes.webp",
    category: "salud-mujer",
    order: 9,
  },
  {
    id: "salud-hombre",
    slug: "salud-hombre",
    title: "Exámenes del Hombre: PSA y Testosterona",
    shortTitle: "Salud Hombre",
    icon: "Mars",
    image: "/images/services/salud-hombre.webp",
    category: "medicina-general",
    order: 10,
  },
  {
    id: "examenes-sangre",
    slug: "examenes-sangre",
    title: "Exámenes y Análisis de Sangre | Laboratorio",
    shortTitle: "Sangre",
    icon: "FlaskConical",
    image: "/images/services/examenes-sangre.webp",
    category: "laboratorio",
    highlighted: true,
    order: 11,
  },
  {
    id: "infecciones-urinarias",
    slug: "infecciones-urinarias",
    title: "Examen de Orina y Tratamiento de Infecciones Urinarias",
    shortTitle: "Urinarias",
    icon: "Droplet",
    image: "/images/services/infecciones-urinarias.webp",
    category: "tratamientos",
    order: 12,
  },
  {
    id: "examen-heces",
    slug: "examen-heces",
    title: "Exámenes de Heces Fecales",
    shortTitle: "Heces",
    icon: "TestTubes",
    image: "/images/services/examen-heces.webp",
    category: "laboratorio",
    order: 13,
  },
  {
    id: "prueba-strep",
    slug: "prueba-strep",
    title: "Prueba de Estreptococo (Strep Test)",
    shortTitle: "Strep",
    icon: "TestTube",
    image: "/images/services/prueba-strep.webp",
    category: "laboratorio",
    order: 14,
  },
  {
    id: "prueba-tuberculosis",
    slug: "prueba-tuberculosis",
    title: "Examen de Tuberculosis (TB)",
    shortTitle: "Tuberculosis",
    icon: "ShieldPlus",
    image: "/images/services/prueba-tuberculosis.webp",
    category: "laboratorio",
    order: 15,
  },
  {
    id: "enfermedades-transmision-sexual",
    slug: "enfermedades-transmision-sexual",
    title: "Pruebas de Enfermedades de Transmisión Sexual (STD)",
    shortTitle: "ETS/STD",
    icon: "ShieldCheck",
    image: "/images/services/enfermedades-transmision-sexual.webp",
    category: "laboratorio",
    order: 16,
  },
  {
    id: "examen-alcohol-drogas",
    slug: "examen-alcohol-drogas",
    title: "Exámenes de Alcohol y Drogas",
    shortTitle: "Alcohol y Drogas",
    icon: "Beaker",
    image: "/images/services/examen-alcohol-drogas.webp",
    category: "examenes",
    order: 17,
  },
  {
    id: "electrocardiograma",
    slug: "electrocardiograma",
    title: "Electrocardiograma (EKG)",
    shortTitle: "Electro (EKG)",
    icon: "HeartPulse",
    image: "/images/services/electrocardiograma.webp",
    category: "laboratorio",
    order: 18,
  },
  {
    id: "ultrasonido",
    slug: "ultrasonido",
    related: ["ginecologia", "prueba-embarazo", "examenes-sangre", "condiciones-cronicas"],
    title: "Ultrasonido de Embarazo y Ecografía en Houston",
    shortTitle: "Ultrasonido",
    icon: "ScanLine",
    image: "/images/services/ultrasonido.webp",
    category: "laboratorio",
    highlighted: true,
    order: 19,
  },
  {
    id: "examen-dot",
    slug: "examen-dot",
    title: "Examen Físico DOT - Licencia CDL",
    shortTitle: "Examen DOT",
    icon: "Truck",
    image: "/images/services/examen-dot.webp",
    category: "examenes",
    order: 20,
  },
  {
    id: "examenes-inmigracion",
    slug: "examenes-inmigracion",
    related: ["vacunas", "prueba-tuberculosis", "examenes-sangre", "electrocardiograma"],
    title: "Examen Médico de Inmigración I-693",
    shortTitle: "Inmigración",
    icon: "ClipboardCheck",
    image: "/images/services/examenes-inmigracion.webp",
    category: "examenes",
    highlighted: true,
    order: 21,
  },
  {
    id: "vacunas",
    slug: "vacunas",
    related: ["prueba-tuberculosis", "examenes-inmigracion", "examen-fisico-escolar", "enfermedades-respiratorias"],
    title: "Vacuna contra la Gripe (Flu Shot) y Tétanos en Houston",
    shortTitle: "Vacunas",
    icon: "Syringe",
    image: "/images/services/vacunas.webp",
    category: "tratamientos",
    order: 22,
  },
  {
    id: "sueros-vitaminados",
    slug: "sueros-vitaminados",
    related: ["examenes-sangre", "tiroides", "condiciones-cronicas", "vacunas"],
    title: "Sueros Vitaminados en Houston: Suero con Vitaminas IV",
    shortTitle: "Sueros",
    icon: "Droplets",
    image: "/images/services/sueros-vitaminados.webp",
    category: "tratamientos",
    order: 23,
  },
  {
    id: "suturas-heridas",
    slug: "suturas-heridas",
    title: "Suturas de Heridas",
    shortTitle: "Suturas",
    icon: "Scissors",
    image: "/images/services/suturas-heridas.webp",
    category: "tratamientos",
    order: 24,
  },
  {
    id: "curacion-heridas",
    slug: "curacion-heridas",
    title: "Cura y Curación de Heridas",
    shortTitle: "Curación",
    icon: "Bandage",
    image: "/images/services/curacion-heridas.webp",
    category: "tratamientos",
    order: 25,
  },
  {
    id: "cirugias-menores",
    slug: "cirugias-menores",
    title: "Cirugías Menores",
    shortTitle: "Cirugías Menores",
    icon: "Stethoscope",
    image: "/images/services/cirugias-menores.webp",
    category: "tratamientos",
    order: 26,
  },
  {
    id: "drenaje-abscesos",
    slug: "drenaje-abscesos",
    title: "Drenaje de Abscesos",
    shortTitle: "Abscesos",
    icon: "Droplet",
    image: "/images/services/drenaje-abscesos.webp",
    category: "tratamientos",
    order: 27,
  },
  {
    id: "unas-encarnadas",
    slug: "unas-encarnadas",
    related: ["cirugias-menores", "drenaje-abscesos", "suturas-heridas", "curacion-heridas"],
    title: "Extracción de Uña Encarnada en Houston",
    shortTitle: "Uñas Encarnadas",
    icon: "Footprints",
    image: "/images/services/unas-encarnadas.webp",
    category: "tratamientos",
    order: 28,
  },
  {
    id: "farmacia",
    slug: "farmacia",
    title: "Farmacia",
    shortTitle: "Farmacia",
    icon: "Pill",
    image: "/images/services/farmacia.webp",
    category: "tratamientos",
    order: 29,
  },
];

export const PROMOTIONS: Promotion[] = [
  {
    slug: "chequeo-general",
    title: "Chequeo General Completo",
    titleEn: "Complete General Checkup",
    price: "$99",
    blurb: "Un repaso completo de tu salud en una sola visita en Spring Branch: análisis general de sangre, hemoglobina A1C y examen general de orina, y la consulta médica va incluida sin costo. Precio de promoción $99 (valor regular $250); confírmalo por teléfono.",
    blurbEn: "A full look at your health in one visit in Spring Branch: a general blood panel, hemoglobin A1C and a urinalysis, with the medical visit included at no charge. Promotional price $99 (regular value $250); confirm it by phone.",
    includes: ["Examen general de sangre","A1C (hemoglobina glicosilada)","Examen general de orina","Consulta médica gratis"],
    includesEn: ["Complete blood panel","A1C (glycated hemoglobin)","Complete urinalysis","Free medical consultation"],
    alt: "Promoción Chequeo General Completo por $99 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Complete General Checkup promotion for $99 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "chequeo-mujer",
    title: "Chequeo Completo de la Mujer",
    titleEn: "Complete Women's Checkup",
    price: "$179",
    blurb: "Cuida tu salud con un chequeo integral femenino en español. Valor regular de $300, ahora por solo $179. Incluye ultrasonido pélvico, examen de Papanicolau y examen de orina, con consulta médica gratis.",
    blurbEn: "Care for your health with a complete women's checkup in Spanish. Regular value of $300, now for only $179. Includes a pelvic ultrasound, a Pap smear and a urinalysis, with a free medical consultation.",
    includes: ["Ultrasonido pélvico","Examen de Papanicolau","Examen de orina","Consulta médica gratis"],
    includesEn: ["Pelvic ultrasound","Pap smear","Urinalysis","Free medical consultation"],
    alt: "Promoción Chequeo Completo de la Mujer por $179 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Complete Women's Checkup promotion for $179 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "examen-hombres",
    title: "Examen Completo para Hombres",
    titleEn: "Complete Men's Exam",
    price: "$89",
    blurb: "Chequeo de salud masculina enfocado en prevención. Incluye examen de orina, examen de próstata para prevención de cáncer y examen de testosterona, con consulta médica gratis.",
    blurbEn: "Men's health checkup focused on prevention. Includes a urinalysis, a prostate exam for cancer prevention and a testosterone test, with a free medical consultation.",
    includes: ["Examen de orina","Examen de próstata (prevención de cáncer)","Examen de testosterona","Consulta médica gratis"],
    includesEn: ["Urinalysis","Prostate exam (cancer prevention)","Testosterone test","Free medical consultation"],
    alt: "Promoción Examen Completo para Hombres por $89 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Complete Men's Exam promotion for $89 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "salud-intima-femenina",
    title: "Salud Íntima Femenina",
    titleEn: "Women's Intimate Health",
    price: "$69",
    blurb: "¿Picazón, flujo o mal olor? Podría ser una infección. Evaluamos tu salud íntima con atención profesional en español y un plan claro para tu tratamiento.",
    blurbEn: "Itching, discharge or odor? It could be an infection. We evaluate your intimate health with professional care in Spanish and a clear treatment plan.",
    includes: ["Cultivo íntimo","Consulta médica","Examen de orina gratis"],
    includesEn: ["Intimate culture test","Medical consultation","Free urinalysis"],
    alt: "Promoción Salud Íntima Femenina por $69 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Women's Intimate Health promotion for $69 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "perfil-hormonal-hombres",
    title: "Perfil Hormonal para Hombres",
    titleEn: "Men's Hormone Panel",
    price: "$200",
    blurb: "Evalúa tu salud hormonal masculina. Útil si notas fatiga, cambios de ánimo, problemas de sueño, pérdida de masa muscular o baja libido. Exámenes confiables con atención profesional.",
    blurbEn: "Evaluate your male hormonal health. Helpful if you notice fatigue, mood changes, sleep problems, muscle loss or low libido. Reliable testing with professional care.",
    includes: ["Perfil hormonal masculino","Exámenes confiables","Resultados precisos","Atención profesional"],
    includesEn: ["Male hormone panel","Reliable testing","Accurate results","Professional care"],
    alt: "Promoción Perfil Hormonal para Hombres por $200 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Men's Hormone Panel promotion for $200 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "sangre-b12",
    title: "General de Sangre + Vitamina B12",
    titleEn: "Blood Panel + Vitamin B12",
    price: "$99",
    blurb: "Promoción especial: examen general de sangre más una inyección de vitamina B12 para apoyar tu energía y bienestar.",
    blurbEn: "Special promotion: a complete blood panel plus a vitamin B12 injection to support your energy and wellbeing.",
    includes: ["Examen general de sangre","Inyección de vitamina B12"],
    includesEn: ["Complete blood panel","Vitamin B12 injection"],
    alt: "Promoción General de Sangre más Vitamina B12 por $99 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Blood Panel plus Vitamin B12 promotion for $99 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
  {
    slug: "examen-testosterona",
    title: "Revisa tu Testosterona",
    titleEn: "Check Your Testosterone",
    price: "$79",
    blurb: "Si notas cansancio, menos energía o cambios en el deseo sexual o en la erección, este paquete mide tu testosterona en sangre y añade un examen de orina; la consulta médica para revisar los resultados no tiene costo. Promoción $79 (precio regular $220); confírmala por teléfono.",
    blurbEn: "If you have noticed fatigue, lower energy or changes in sex drive or erections, this package measures your blood testosterone and adds a urinalysis; the medical visit to go over the results is free. Promotion $79 (regular price $220); confirm it by phone.",
    includes: ["Examen de testosterona","Examen de orina","Consulta médica gratis"],
    includesEn: ["Testosterone test","Urinalysis","Free medical consultation"],
    alt: "Promoción Examen de Testosterona por $79 en Clínica Hispana Nueva Salud Gessner, Houston",
    altEn: "Testosterone Test promotion for $79 at Clínica Hispana Nueva Salud Gessner, Houston",
  },
];

export const GREEN_CARD_FEATURES: GreenCardFeature[] = [
  { id: "1", text: "Médico Civil Surgeon certificado por USCIS", included: true },
  { id: "2", text: "Formulario I-693 completado y sellado", included: true },
  { id: "3", text: "Examen físico completo", included: true },
  { id: "4", text: "Análisis de sangre requeridos", included: true },
  { id: "5", text: "Historial de vacunas revisado", included: true },
  { id: "6", text: "Resultados en 3-5 días hábiles", included: true },
  { id: "7", text: "Atención 100% en español", included: true },
  { id: "8", text: "Sin cita previa necesaria", included: true },
];



